<a href="https://colab.research.google.com/github/liupengzhouyi/LearningColaboratory/blob/master/RNN_%E5%AE%9E%E7%8E%B0%E6%89%8B%E5%86%99%E6%95%B0%E5%AD%97%E8%AF%86%E5%88%AB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# RNN 实现手写数字识别

## Improt package

In [0]:
import torch
import torchvision

## Download train data

In [0]:
train_data = torchvision.datasets.MNIST(
    root='./mnist/',
    train=True,
    transform=torchvision.transforms.ToTensor(),
    download=True
)

## Create train data set

In [0]:
train_data_set = torch.utils.data.DataLoader(dataset=train_data, batch_size=50, shuffle=True)

## Dwnload test data

In [0]:
test_data = torchvision.datasets.MNIST(
    root='./mnist/',
    train=False,
)

## Create test data set

In [5]:
test_x = torch.unsqueeze(test_data.test_data, dim=1).type(torch.FloatTensor)[:2000]/255.
test_y = test_data.test_labels[:2000]

/usr/local/lib/python3.6/dist-packages/torchvision/datasets/mnist.py:60: UserWarning: test_data has been renamed data
  warnings.warn("test_data has been renamed data")
/usr/local/lib/python3.6/dist-packages/torchvision/datasets/mnist.py:50: UserWarning: test_labels has been renamed targets
  warnings.warn("test_labels has been renamed targets")


## Create RNN Model

In [0]:
class LpRnnModel(torch.nn.Module):
    def __init__(self):
        super(LpRnnModel, self).__init__()
        self.rnn = torch.nn.LSTM(
            input_size=28,
            hidden_size=64,
            num_layers=1,
            batch_first=True,
        )
        self.out = torch.nn.Linear(64, 10)

    def forward(self, input):
        r_out, (h_n, h_c) = self.rnn(input, None)
        out = self.out(r_out[:, -1, :])
        return out

## Instantiation LpRnnModel

In [0]:
model = LpRnnModel()

## show Model

In [8]:
print(model)

LpRnnModel(
  (rnn): LSTM(28, 64, batch_first=True)
  (out): Linear(in_features=64, out_features=10, bias=True)
)


## Create Optimizer

In [0]:
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

## Create loss function

In [0]:
loss_function = torch.nn.CrossEntropyLoss()

## Train data

In [13]:
for epoch in range(4):
    for step, (images, labels) in enumerate(train_data_set):
        images = images.view(-1, 28, 28)
        output = model(images)
        loss = loss_function(output, labels)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        if step % 100 == 0:
            print('step:', step)


step: 0
step: 100
step: 200
step: 300
step: 400
step: 500
step: 600
step: 700
step: 800
step: 900
step: 1000
step: 1100
step: 0
step: 100
step: 200
step: 300
step: 400
step: 500
step: 600
step: 700
step: 800
step: 900
step: 1000
step: 1100
step: 0
step: 100
step: 200
step: 300
step: 400
step: 500
step: 600
step: 700
step: 800
step: 900
step: 1000
step: 1100
step: 0
step: 100
step: 200
step: 300
step: 400
step: 500
step: 600
step: 700
step: 800
step: 900
step: 1000
step: 1100


## test model

In [20]:
output = model(test_x.view(-1, 28,28))
print(output)
pred = torch.max(output, 1)[1].data.numpy()
print(pred)
print(test_y)
sumValue = 0.
for index in range(2000):
    if pred[index] == test_y[index]:
        sumValue = sumValue + 1.0
    else:
        print(index, pred[index], test_y[index])

accuracy = float(sumValue / float(len(test_y)))
print('accuracy:', accuracy)

tensor([[-4.1714, -0.2464, -0.9364,  ...,  9.6694, -1.7851, -0.7958],
        [-3.0445,  1.6241,  9.5984,  ...,  1.1316, -0.1400, -3.7524],
        [-2.7030, 11.9562,  0.5728,  ..., -0.0198,  0.6804, -3.8697],
        ...,
        [-4.1268, -1.8262,  0.7363,  ...,  0.1944, -0.8013,  0.6800],
        [-0.7457, -7.8021, -1.3889,  ..., -0.8667, -1.8408,  9.4213],
        [-3.8454, -4.0696, -2.7068,  ..., -1.1696, -0.4562,  3.7685]],
       grad_fn=<AddmmBackward>)
[7 2 1 ... 3 9 5]
tensor([7, 2, 1,  ..., 3, 9, 5])
8 6 tensor(5)
149 9 tensor(2)
184 3 tensor(8)
200 2 tensor(3)
236 7 tensor(2)
247 6 tensor(4)
266 0 tensor(8)
287 7 tensor(4)
321 7 tensor(2)
358 4 tensor(7)
394 7 tensor(9)
435 9 tensor(8)
445 0 tensor(6)
449 5 tensor(3)
508 5 tensor(6)
571 9 tensor(4)
582 2 tensor(8)
583 7 tensor(2)
613 3 tensor(2)
619 8 tensor(1)
659 7 tensor(2)
707 9 tensor(4)
716 7 tensor(1)
839 3 tensor(8)
881 9 tensor(4)
900 3 tensor(1)
926 0 tensor(2)
947 9 tensor(8)
951 9 tensor(5)
1014 5 tensor(6)
1039