<a href="https://colab.research.google.com/github/liupengzhouyi/LearningColaboratory/blob/master/20200627/Numpy%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 快速入门

## create Numpy Object

In [11]:
import numpy as np
object0 = np.arange(1, 21)
print(object0)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


## create Numpy By function array()

In [12]:
# list
object1 = np.array([1,2,3])
print(object1)
# tuple
object2 = np.array((2.2,3,4))
print(object2)

[1 2 3]
[2.2 3.  4. ]


## Setting Numpy Object Data Type When You Create Numpy Object

In [13]:
object3 = np.array([123,456], dtype=np.float32)
print(type(object3))
print(object3.dtype)

<class 'numpy.ndarray'>
float32


## Create Zeros Numpy Object


In [14]:
object4 = np.zeros((5, 7))
print(object4)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


## create Ones Numpy Object

In [15]:
object5 = np.ones((3, 4))
print(object5)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Create Range Numpy Object

In [26]:
object6 = np.empty((3, 2, 4))
print(object6)

[[[1.25136e-316 0.00000e+000 0.00000e+000 0.00000e+000]
  [0.00000e+000 0.00000e+000 0.00000e+000 0.00000e+000]]

 [[0.00000e+000 0.00000e+000 0.00000e+000 0.00000e+000]
  [0.00000e+000 0.00000e+000 0.00000e+000 0.00000e+000]]

 [[0.00000e+000 0.00000e+000 0.00000e+000 0.00000e+000]
  [0.00000e+000 0.00000e+000 0.00000e+000 0.00000e+000]]]


## Show Numpy Shape

In [27]:
print(object6.shape)

(3, 2, 4)


## change numpy shape

In [28]:
object6 = object6.reshape(4, 6)
print(object6)

[[1.25136e-316 0.00000e+000 0.00000e+000 0.00000e+000 0.00000e+000
  0.00000e+000]
 [0.00000e+000 0.00000e+000 0.00000e+000 0.00000e+000 0.00000e+000
  0.00000e+000]
 [0.00000e+000 0.00000e+000 0.00000e+000 0.00000e+000 0.00000e+000
  0.00000e+000]
 [0.00000e+000 0.00000e+000 0.00000e+000 0.00000e+000 0.00000e+000
  0.00000e+000]]


## Show Numpy Date Type

In [19]:
# print(object0.dtype)
print(object0.dtype.name)

int64


## Show Item Size

In [20]:
print(object0.itemsize)

8


## Show Numpy Object Size

In [21]:
print(object0.size)

20


## Show Object Type

In [22]:
print(type(object0))

<class 'numpy.ndarray'>


## List To Numpy

In [23]:
tempList2 = list(range(1, 11))
print(tempList2)
newNumpyObject2 = np.array(tempList2)
print(newNumpyObject2)
print(type(newNumpyObject2))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


## Tuple To Numpy

In [24]:
tempList1 = tuple(range(1, 11))
print(tempList1)
newNumpyObject1 = np.array(tempList1)
print(newNumpyObject1)
print(type(newNumpyObject1))

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


## Numpy Create Array

* return array type 

In [34]:
object7 = np.arange(3)
print(object7)
print(object7.dtype)

[0 1 2]
int64
