# Numpy Shape

## Create Numpy Object

In [42]:
import numpy
object301 = numpy.arange(12)
print(object301)
print(object301.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)


## Reset Numpy Object Shape

In [43]:
object301 = object301.reshape(2, 6)
print(object301)
print(object301.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
(2, 6)


## Stack Matrix
![替代文字](https://tva1.sinaimg.cn/large/007S8ZIlly1gg98adasgaj30gg07gmx3.jpg)



In [44]:
object302 = numpy.floor(10*numpy.random.random((2, 2)))
object303 = numpy.floor(10*numpy.random.random((2, 2)))
print(object302)
print(object303)
object304 = numpy.vstack((object302, object303))
print(object304)
object305 = numpy.hstack((object302, object303))
print(object305)

[[7. 2.]
 [5. 3.]]
[[9. 8.]
 [1. 9.]]
[[7. 2.]
 [5. 3.]
 [9. 8.]
 [1. 9.]]
[[7. 2. 9. 8.]
 [5. 3. 1. 9.]]


## Split Numpy Object

In [45]:
object306 = numpy.arange(25, dtype=numpy.int16)
print(object306)
object306 = object306.reshape(5, 5)
print(object306)
print(numpy.hsplit(object306, (2, 3)))
print(numpy.vsplit(object306, (2, 3)))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16],
       [20, 21]], dtype=int16), array([[ 2],
       [ 7],
       [12],
       [17],
       [22]], dtype=int16), array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19],
       [23, 24]], dtype=int16)]
[array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]], dtype=int16), array([[10, 11, 12, 13, 14]], dtype=int16), array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]], dtype=int16)]


## Copy Numpy 

In [46]:
object307 = numpy.arange(20)
object307.reshape(4, 5)
object308 = object307.copy()
print(object307 is object308)

False
