<a href="https://colab.research.google.com/github/liupengzhouyi/LearningColaboratory/blob/master/20200629/Numpy_%E6%93%8D%E4%BD%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Operating Numpy Object 

## Create Numpy Object

In [ ]:
import numpy
object21 = numpy.array([20, 30, 40, 50])
print(object21)
object22 = numpy.arange(4)
print(object22)

[20 30 40 50]


## Add

In [ ]:
object23 = object21 + object22
print(object23)

[20 31 42 53]


## Substruction

In [ ]:
object24 = object21 - object22;
print(object24)

[20 29 38 47]


## Power

In [ ]:
object25 = object22 ** 2
print(object25)

[0 1 4 9]


##Multiplicaion Item In Matrix 

In [ ]:
object26 = numpy.array([[1, 2], [3, 4]])
object27 = numpy.array([[2, 3], [4, 1]])
print(object26)
print(object27)

object28 = object26 * object27
print(object28)

[[1 2]
 [3 4]]
[[2 3]
 [4 1]]
[[ 2  6]
 [12  4]]


## Multiplication Of matrix

In [ ]:
object29 = object26 @ object27
print(object29)
object210 = object26.dot(object27)
print(object210)

[[10  5]
 [22 13]]
[[10  5]
 [22 13]]


## Operating in ord Matrix

In [ ]:
object211 = numpy.arange(4).reshape(2, 2)
print(object211)
object211 += 2
print(object211)


[[0 1]
 [2 3]]
[[2 3]
 [4 5]]


## Get Max

In [ ]:
print(object211.max())

5


## Get Min

In [ ]:
print(object211.min())

2


## Get sum

In [ ]:
print(object211.sum())

14


## Specified axis

In [ ]:
object212 = numpy.arange(20).reshape(4,5)
print(object212)
print(object212.sum(axis=0))
print(object212.sum(axis=1))
print(object212.max(axis=0))
print(object212.max(axis=1))
print(object212.min(axis=0))
print(object212.min(axis=1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[30 34 38 42 46]
[10 35 60 85]
[15 16 17 18 19]
[ 4  9 14 19]
[0 1 2 3 4]
[ 0  5 10 15]


## index

In [ ]:
object213 = numpy.arange(20)
print(object213)
if len(object213) > 3:
    print(object213[3])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
3


## Sliced

In [ ]:
print(object213[15:2:-3])
print(object213[1:12:2])

[15 12  9  6  3]
[ 1  3  5  7  9 11]
